theme = "hermit_zola"
# The URL the site will be built for
base_url = "https://LeCodeEtMoi.github.io/MonBlog/"

# Used in RSS by default
title = "Le Blog du Pingouin"
description = "My blog"
# The default language, used in RSS
default_language = "fr"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
home_subtitle = "Ce qui doit arriver arrivera -Spike Spigeal"

home_logo = "https://cdn-icons-png.freepik.com/512/1805/1805806.png?ga=GA1.1.795171737.1713953483"

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/tutoriels", name = "Tutoriels" },
    { link = "/maths_nsi", name = "Maths NSI" },
    { link = "/jazz", name = "Musique et compr√©hension" },
    { link = "/about", name = "About" },
]

hermit_social = [
    { name = "github", link = "https://github.com/LeCodeEtMoi/MonBlog" },
    { name = "email", link = "mailto:author@domain.com" }
]


[extra.author]
name = "LaPetiteLigneDeCode"



